version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: taskflow-backend
    ports:
      - "2500:2500"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: http://localhost:2500
        VITE_API_BASE_URL: /api
    container_name: taskflow-frontend
    ports:
      - "2000:2000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped